// Sessions
export const RETRIEVE_SESSIONS = "RETRIEVE_SESSIONS";
export const RETRIEVE_SINGLE_SESSION = "RETRIEVE_SINGLE_SESSION";

// Exercise Units
export const ADD_EXERCISE_UNIT = "ADD_EXERCISE_UNIT";
export const DELETE_EXERCISE_UNIT = "DELETE_EXERCISE_UNIT";
