// Sessions
export const RETRIEVE_SESSIONS = "RETRIEVE_SESSIONS";

export const RETRIEVE_SINGLE_SESSION_REQUEST =
  "RETRIEVE_SINGLE_SESSION_REQUEST";
export const RETRIEVE_SINGLE_SESSION_SUCCESS =
  "RETRIEVE_SINGLE_SESSION_SUCCESS";
export const RETRIEVE_SINGLE_SESSION_FAIL = "RETRIEVE_SINGLE_SESSION_FAIL";

export const ADD_SESSION_REQUEST = "ADD_SESSION_REQUEST";
export const ADD_SESSION_SUCCESS = "ADD_SESSION_SUCCESS";
export const ADD_SESSION_FAIL = "ADD_SESSION_FAIL";

export const LIKE_SESSION_REQUEST = "LIKE_SESSION_REQUEST";
export const LIKE_SESSION_SUCCESS = "LIKE_SESSION_SUCCESS";
export const LIKE_SESSION_FAIL = "LIKE_SESSION_FAIL";

export const UPDATE_SESSION_REQUEST = "UPDATE_SESSION_REQUEST";
export const UPDATE_SESSION_SUCCESS = "UPDATE_SESSION_SUCCESS";
export const UPDATE_SESSION_FAIL = "UPDATE_SESSION_FAIL";

export const DELETE_SESSION = "DELETE_SESSION";

// Exercise Units
export const ADD_EXERCISE_UNIT = "ADD_EXERCISE_UNIT";
export const DELETE_EXERCISE_UNIT = "DELETE_EXERCISE_UNIT";

// Sets
export const ADD_SET = "ADD_SET";
export const DELETE_SET = "DELETE_SET";
export const UPDATE_SET = "UPDATE_SET";

// Exercises
export const RETRIEVE_EXERCISES = "RETRIEVE_EXERCISES";

// Auth
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";

export const AUTH_ERROR = "AUTH_ERROR";
export const LOGOUT = "LOGOUT";

// User
export const RETRIEVE_USER = "RETRIEVE_USER";
export const SEARCH_USERS = "SEARCH_USERS";
export const SEARCH_USERS_SUCCESS = "SEARCH_USERS_SUCCESS";
export const SEARCH_USERS_FAILURE = "SEARCH_USERS_FAILURE";

// metric
export const TOGGLE_METRIC = "TOGGLE_METRIC";
